### ISSUE TITLE
Reply message after command execution disappears after switching tabs

### ISSUE THREAD

**Issue by ginloy** [AY2223S2-CS2103-W17-4/tp#110]
1) After using find command, correct feedback appears on reply box.
2) After switching tabs, feedback changes to "Currently listing all x"

**Comment by ginloy** [comment]
@kimberlybp is this backend or frontend problem

**Comment by kimberlybp** [comment]
err frontend hahah the way i implemented it was the tabs only contain messages relevant to that item, eg. customer is listing all, but vehicle is currently viewing a specific vehicle

**Comment by kimberlybp** [comment]
but last shown command result should still show tho, will look into it
