### ISSUE TITLE
[PE-D][Tester C] Technician doesn't show up after adding

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W17-4/tp#122]
![image.png](https://raw.githubusercontent.com/zm-l/ped/main/files/5a7833cf-0da0-468d-b176-ab35b313e50a.png)

1. Run `addtechnician`
2. The screen loads to technician tab but it is empty.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: zm-l/ped#2

**Comment by kimberlybp** [comment]
GUI Bug, but also related to hashCode of technicians/staff
