### ISSUE TITLE
[PE-D][Tester C] User guide functionality is different

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W17-4/tp#124]
![image.png](https://raw.githubusercontent.com/zm-l/ped/main/files/d64a70cf-76c4-43c2-bcac-79b7d0cecf20.png)

The input described in the user guide is different from the app.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: zm-l/ped#3

**Comment by kimberlybp** [comment]
Need to update UG to match app functionality, UG doesnt specify they need to indicate color**
