### ISSUE TITLE
[PE-D][Tester C] Customer display only shows customer id 1.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-4/tp#127]
![image.png](https://raw.githubusercontent.com/zm-l/ped/main/files/4e1a647f-47e1-4b03-9493-01da63072b80.png)

1. Even when customer 7 was pressed, the display shows customer 1.

Every other tab like vehicles also has similar problem.

Edit: after reading further, I think the viewing should be done through view command, I think the view command should be added in front as it might be confusing for user

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: zm-l/ped#6

**Comment by kimberlybp** [comment]
- Need to clarify in UG that clicking does not change selected object in view details panel
- Move View command instructions up in UG(?)

**Comment by kimberlybp** [comment]
also fixed in pr #151
