### ISSUE TITLE
[PE-D][Tester B] [editvehicle] Command accepts empty p/ argument

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W17-4/tp#133]
Command
```
editvehicle i/2 p/
```

Log:
```
Result: Edited vehicle: ID: 1
Owner: 1
Plate:
Color: Red
Brand: Toyota Corolla
Type: Car
Services:
```

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: c0j0s/ped#7

**Comment by kimberlybp** [comment]
Need to validate that 😯 double check rest of params too

**Comment by 9fc70c892** [comment]
This is "not a bug"

Jk, it's missing parsing of string
